name: inverti_app
description: Aplicación Flutter para conectar inversionistas con emprendedores
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase completo (Plan Spark gratuito) - VERSIONES ACTUALIZADAS
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.9.4  # Compatible con notificaciones push
  
  # Autenticación (Google + Email obligatorios)
  google_sign_in: ^6.2.1
  
  # Gestión de estado (obligatorio - NO setState)
  provider: ^6.1.2
  
  # UI y mapas (obligatorios)
  google_maps_flutter: ^2.6.1
  cached_network_image: ^3.3.1  # Para imágenes offline
  image_picker: ^1.1.2
  
  # Temas y fuentes personalizadas (obligatorio)
  shared_preferences: ^2.2.3
  
  # Conectividad (para imágenes offline)
  connectivity_plus: ^6.0.3
  
  # Simulación de pagos (obligatorio - solo UI)
  flutter_credit_card: ^4.0.1
  
  # Animaciones básicas
  lottie: ^3.1.2
  
  # Toque creativo - Quick Pitch
  record: ^5.1.0
  audioplayers: ^6.0.0
  
  # NUEVAS DEPENDENCIAS PARA TIEMPO REAL Y NOTIFICACIONES
  flutter_local_notifications: ^17.2.3  # Notificaciones locales
  permission_handler: ^11.3.1           # Gestión de permisos
  
  # Utilidades
  intl: ^0.19.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/images/ui/
    - assets/animations/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700