name: inverti_app
description: Aplicaci贸n Flutter para conectar inversionistas con emprendedores
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase completo
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.9.4
  
  # Autenticaci贸n
  google_sign_in: ^6.2.1
  
  # Gesti贸n de estado
  provider: ^6.1.2
  http: ^1.1.0
  googleapis_auth: ^1.4.1
  # UI y mapas
  google_maps_flutter: ^2.6.1
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  
  # Temas y fuentes
  shared_preferences: ^2.2.3
  
  # Conectividad
  connectivity_plus: ^6.0.3
  
  # Simulaci贸n de pagos
  flutter_credit_card: ^4.0.1
  
  # Animaciones
  lottie: ^3.1.2
  
  # Quick Pitch
  record: ^5.1.0
  audioplayers: ^6.0.0
  
  # Notificaciones y permisos
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  
  # Utilidades
  intl: ^0.19.0
  path_provider: ^2.1.3
  flutter_svg: ^2.0.10
  url_launcher: ^6.3.0
  photo_view: ^0.14.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/images/ui/
    - assets/animations/
    - assets/images/placeholders/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    
  #  - family: InvertiIcons
  #    fonts:
  #      - asset: assets/fonts/InvertiIcons.ttf

dependency_overrides:
  web: ^0.1.4-beta